<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistem Presensi Berbasis Fingerprint</title>
    <link rel="stylesheet" href="style login.css">
</head>
<body>
    <nav>
        <div class="wrapper">
            <div class="logo"><a href="index.php">Institut Teknologi Nasional</a></div>
            <div class="menu">
                <ul>
                    <li><a href="#Home">Home</a></li>
                    <li><a href="#Contact">Contact</a></li>
                    <li><a href="login.php">Login</a></li>
                    <li><a href="signup.php" class="tbl-orange">Sign Up</a></li>
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="wrapper">
        <section id="Home">
            <img src="https://img.freepik.com/free-vector/software-development-team-concept-illustration_335657-5545.jpg" alt="Ilustrasi Sistem Presensi"/>
            <div class="kolom">
                <p class="deskripsi">Selamat Datang di</p>
                <h2>Sistem Presensi Berbasis Fingerprint</h2>
                <p>Sistem Presensi Berbasis Fingerprint di universitas merupakan inovasi teknologi yang digunakan untuk mencatat kehadiran mahasiswa secara otomatis dan akurat melalui pemindaian sidik jari. Sistem ini memastikan kehadiran yang valid karena setiap sidik jari bersifat unik, sehingga meminimalkan kecurangan seperti titip absen. Data kehadiran tersimpan langsung dalam basis data terpusat dan dapat diakses oleh dosen maupun pihak administrasi untuk pemantauan real time. Dengan penerapan sistem ini, proses absensi menjadi lebih efisien, transparan, serta mendukung transformasi universitas menuju lingkungan akademik digital yang modern dan tertib.</p>
                <p><a href="" class="tbl-biru">Pelajari Lebih Lanjut</a></p>
            </div>
        </section>
    </div>

    <div id="Contact">
        <div class="wrapper">
            <div class="footer">
                <div class="footer-section">
                    <h3>Itenas</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui, accusamus.</p>
                </div>
                <div class="footer-section">
                    <h3>Contact</h3>
                    <p>Jl. PKH. Hasan Mustopha No.23 Bandung</p>
                    <p>Kode Pos: 40124, Indonesia</p>
                    <p>Phone : +62 22 7272215 ext 275</p>
                    <p>E-mail : spp@itenas.ac.id</p>
                </div>
                <div class="footer-section">
                    <h3>Social</h3>
                    <p>Instagram : Itenas.official</p>
                    <p>Facebook : Itenas.official</p>
                    <p>Tiktok : itenasofficial</p>
                </div>
            </div>
        </div>
    </div>

    <div id="copyright">
        <div class="wrapper">
            &copy; <?php echo date("Y"); ?>. <b>Institut Teknologi Nasional Bandung</b> All Rights Reserved.
        </div>
    </div>
</body>
</html>